config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings
  get 'home/index'

  
  

  root 'home#index'

  get '/auth/facebook/callback' => 'session#create'

end

app/models/listing.rb
require 'carrierwave/orm/activerecord'

class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :listings_tags, dependent: :destroy
	has_many :tags, through: :listings_tags
	attr_accessor :tags_collection
	# validates :title, uniqueness:{case_sensitive:false}, presence:true 
	#validates :title, presence: true
	mount_uploaders :images, ImagesUploader
end

# def all_tags=(names)
#   self.tags = names.split(",").map do |name|
#       Tag.where(name: name.strip).first_or_create!
#   end
# end

# def all_tags
#   self.tags.map(&:name).join(", ")
# end

app/models/listing_rspec.rb
require 'rails helper'

# Rspec.describe.listing, :'type' :'model' do
# 	context 'validates title' do 
		# it { is expected to validate_presence_of(:title)}
		# # it { is expected to validate_uniqueness_of(:title)}
		# it { is expected to ensure_length_of(:title) is at least(25) is atmost(1000)}
	# end
end

app/models/listings_tag.rb
class ListingsTag < ActiveRecord::Base
  belongs_to :listing
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :listings_tags, dependent: :destroy
	has_many :listings, through: :listings_tags

end

app/models/user.rb
require 'carrierwave/orm/activerecord'


class User < ActiveRecord::Base
  include Clearance::User
  	attr_accessor :image
   has_many :listings, dependent: :destroy
   mount_uploader :image, AvatarUploader

   def resize_100
   	image = MiniMagick::Image.open(self.image.current_path)
	image.resize "100x100"
	image.write "avatar.png"
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@listings =Listing.all
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.where(user_id: current_user.id)

  end
  # def listing/:id
  # @listings = Listing.where(user_id: current_user.id)
  # end
  # GET /listings/1
  # GET /listings/1.json
  def show

  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    if current_user
      @listing = current_user.listings.new(listing_params)
    end

    respond_to do |format|
     
      
      if @listing.save

        tags = params[:listing][:tags_collection].split(', ')
        tags.each do |tag|
          a = Tag.find_or_create_by(name: tag)
          a.listings << @listing
        end
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:property_name, :price, :description, :user_id, {images: []})
    end

    def tag_params
      params.require(:listing).permit(:tags)
    end
end

# private
# def post_params
#   params.require(:post).permit(:author, :content, :all_tags)
# end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def create
		auth = request.env['omniauth.auth']
		user = User.find_or_initialize_by(email: auth.info.email)
		user.password = "string"
		user.save!
		sign_in(user)
		redirect_to '/home/index'
	end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_filter :authenticate_user!, except: [:index]
	# def user_params
	# params.require(:user).permit(:email, :first_name, :last_name, :image)
	# end
	def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    image = user_params.delete(:image)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.image = image
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div class="jumbotron">
  <h1>Welcome to Pairbnb</h1>
  <p>We have thousands of properties for short stays in various cities to make you vacation more affordable</p>
  <p><a class="btn btn-primary btn-lg" href="/listings" role="button">Make A Listing</a></p>
</div>
<table class='table table-stripped'>
  
  <thead>
    <tr>
      <th>Property name</th>
      <th>Price</th>
      <th>Description</th>
      <th>User</th>
      <th>Photos of the Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <% @listings.each do |listing| %>
      
      <tr>
        <td><%= listing.property_name %></td>
        <td><%= listing.price %></td>
        <td><%= listing.description %></td>
        <td><%= listing.user.email %></td>

        <td> <% listing.images.each_with_index do |images| %>
      <img src="<%=listing.images[0].url %>"height="42" width="42"/></td>


        
      </tr>
      <% end %>
    <% end %>

  </tbody>
</table>
<p>
  <p>


THIS IS THE INDEX HTML>>IGNORE THE FB LOGIN BELOW>>JUST FOR LEARNING
<br>
<a href="/auth/facebook">Facebook login</a>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairBnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PairBNB </a>
    </div>
     <!-- Collect the nav links, forms, and other content for toggling -->
    


    <div class="navbar-right">

      <% if current_user %>
        <p class="navbar-text "><img src="<%= current_user.image %>"height="42" width="42"/>  Signed in as <%= current_user.email%></p>
      <%end%>
      <ul class="nav navbar-nav">

          <% if current_user %>

            <%= button_to "Sign out", sign_out_path, method: :delete, class: 'btn btn-default navbar-btn' %>
          <% else %>
            <%= button_to "Sign in", sign_in_path, method: :get, class: 'btn btn-default navbar-btn' %>
          <% end %>
        </li>
      </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '221310281535376',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_name %><br>
    <%= f.text_field :property_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="tags">
    <%= f.label :tags %><br>
    <%= f.text_field :tags_collection %>
  </div>
  <p>
  <p>
 
  <%= f.file_field :images, multiple: true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listings</h1>

<table class='table table-stripped'>
  
  <thead>
    <tr>
      <th>Property name</th>
      <th>Price</th>
      <th>Description</th>
      <th>User</th>
      <th>Photos of the Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      
      <tr>
        <td><%= listing.property_name %></td>
        <td><%= listing.price %></td>
        <td><%= listing.description %></td>
        <td><%= listing.user.email %></td>

        <td> <% listing.images.each do |image| %>
      <img src="<%=image.url %>"height="42" width="42"/>
      <% end %>
    </td>

        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property name:</strong>
  <%= @listing.property_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user.email %>
</p>
<p><a class="btn btn-primary btn-lg" href="/listings" role="button">Book It</a></p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/users/new.html.erb
<h1>You're in the users#new to create a new user. This file is located in 'app/views/users/new.html.erb</h1>'

<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
    <%= form.file_field :image %>
    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>

    
  <% end %>
</div>

app/views/users/show.html.erb
<%= image_tag @user.image.url %>